//
//  CreateOrderInteractorTests.swift
//  CleanStore
//
//  Created by IDEAL YANG on 2018/12/14.
//  Copyright (c) 2018 IDEAL YANG. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

@testable import CleanStore
import XCTest

class CreateOrderInteractorTests: XCTestCase
{
  // MARK: Subject under test
  
  var sut: CreateOrderInteractor!
  
  // MARK: Test lifecycle
  
  override func setUp()
  {
    super.setUp()
    setupCreateOrderInteractor()
  }
  
  override func tearDown()
  {
    super.tearDown()
  }
  
  // MARK: Test setup
  
  func setupCreateOrderInteractor()
  {
    sut = CreateOrderInteractor()
  }
  
  // MARK: Test doubles
  
  class CreateOrderPresentationLogicSpy: CreateOrderPresentationLogic
  {
    var presentExpirationDateCalled = false
    
    func presentExpirationDate(response: CreateOrder.FormatExpirationDate.Response) {
        presentExpirationDateCalled = true
    }
    
    var presentSomethingCalled = false
    
    func presentSomething(response: CreateOrder.Something.Response)
    {
      presentSomethingCalled = true
    }
  }
  
  // MARK: Tests
  
  func testDoSomething()
  {
    // Given
    let spy = CreateOrderPresentationLogicSpy()
    sut.presenter = spy
    let request = CreateOrder.Something.Request()
    
    // When
    sut.doSomething(request: request)
    
    // Then
    XCTAssertTrue(spy.presentSomethingCalled, "doSomething(request:) should ask the presenter to format the result")
  }
    
    func testFormatExpirationDateShouldAskPresenterToFormatExpirationDate()
    {
        // Given
        let spy = CreateOrderPresentationLogicSpy()
        sut.presenter = spy
        let request = CreateOrder.FormatExpirationDate.Request(date: Date())
        
        // When
        sut.formatExpirationDate(request: request)
        
        // Then ...
        XCTAssertTrue(spy.presentExpirationDateCalled,"formatExpirationDate(request:) should ask the presenter to format the date")
    }
    
}
