//
//  ListOrdersModels.swift
//  CleanStore
//
//  Created by IDEAL YANG on 2018/12/17.
//  Copyright (c) 2018 IDEAL YANG. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

enum ListOrders
{
  // MARK: Use cases
  
  enum Something
  {
    struct Request
    {
    }
    struct Response
    {
    }
    struct ViewModel
    {
    }
  }
    
    enum FetchOrders {
        struct Request
        {
            
        }
        struct Response
        {
            var orders: [Order]
        }
        struct ViewModel
        {
            struct DisplayedOrder
            {
                var id: String
                var date: String
                var email: String
                var name: String
                var total: String
            }
            var displayedOrders: [DisplayedOrder]
        }
    }
}

struct Order
{
    var id: String
    var date: Date
    var email: String
    var firstName: String
    var lastName: String
    var total: NSDecimalNumber
}
